### ISSUE TITLE
build android error 

### ISSUE THREAD

**Issue by yingnierxiao** [slowburn-dev/DataConfig#10]
UATHelper: Packaging (Android (ASTC)): D:/GitHub/VALORANT/Plugins/DataConfig/Source/DataConfigEngineExtra5/Private/DataConfig/EngineExtra/SerDe/DcSerDeInstancedStruct.cpp(57,20): error: no member named 'HasMetaData' in 'FField'
UATHelper: Packaging (Android (ASTC)):                 if (StructField->HasMetaData(TEXT("BaseStruct")))
UATHelper: Packaging (Android (ASTC)):                     ~~~~~~~~~~~  ^
UATHelper: Packaging (Android (ASTC)): D:/GitHub/VALORANT/Plugins/DataConfig/Source/DataConfigEngineExtra5/Private/DataConfig/EngineExtra/SerDe/DcSerDeInstancedStruct.cpp(59,48): error: no member named 'GetMetaData' in 'FField'
UATHelper: Packaging (Android (ASTC)):                         const FString& BaseStructStr = StructField->GetMetaData(TEXT("BaseStruct"));
UATHelper: Packaging (Android (ASTC)):                                                        ~~~~~~~~~~~  ^
UATHelper: Packaging (Android (ASTC)): 2 errors generated.
UATHelper: Packaging (Android (ASTC)): [2/4] Compile [arm64] Module.DataConfigEngineExtra.cpp
UATHelper: Packaging (Android (ASTC)): In file included from D:/GitHub/VALORANT/Plugins/DataConfig/Intermediate/Build/Android/a/UnrealGame/Development/DataConfigEngineExtra/Module.DataConfigEngineExtra.cpp:8:
UATHelper: Packaging (Android (ASTC)): D:/GitHub/VALORANT/Plugins/DataConfig/Source/DataConfigEngineExtra/Private/DataConfig/EngineExtra/SerDe/DcJsonBlueprintLibrary.cpp(82,72): error: use of undeclared identifier 'PredicateIsBase64Blob'
UATHelper: Packaging (Android (ASTC)):                 Serializer->AddPredicatedHandler(FDcSerializePredicate::CreateStatic(PredicateIsBase64Blob), FDcSerializeDelegate::CreateStatic(HandleBase64BlobSerialize));
UATHelper: Packaging (Android (ASTC)):                                                                                      ^
PackagingResults: Error: no member named 'HasMetaData' in 'FField'
PackagingResults: Error: no member named 'GetMetaData' in 'FField'
PackagingResults: Error: use of undeclared identifier 'PredicateIsBase64Blob'
UATHelper: Packaging (Android (ASTC)): D:/GitHub/VALORANT/Plugins/DataConfig/Source/DataConfigEngineExtra/Private/DataConfig/EngineExtra/SerDe/DcJsonBlueprintLibrary.cpp(82,131): error: use of undeclared identifier 'HandleBase64BlobSerialize'
UATHelper: Packaging (Android (ASTC)):                 Serializer->AddPredicatedHandler(FDcSerializePredicate::CreateStatic(PredicateIsBase64Blob), FDcSerializeDelegate::CreateStatic(HandleBase64BlobSerialize));
UATHelper: Packaging (Android (ASTC)):                                                                                                                                                 ^
UATHelper: Packaging (Android (ASTC)): D:/GitHub/VALORANT/Plugins/DataConfig/Source/DataConfigEngineExtra/Private/DataConfig/EngineExtra/SerDe/DcJsonBlueprintLibrary.cpp(149,76): error: use of undeclared identifier 'PredicateIsBase64Blob'
UATHelper: Packaging (Android (ASTC)):                 Deserializer->AddPredicatedHandler(FDcDeserializePredicate::CreateStatic(PredicateIsBase64Blob), FDcDeserializeDelegate::CreateStatic(HandleBase64BlobDeserialize));
UATHelper: Packaging (Android (ASTC)):                                                                                          ^
UATHelper: Packaging (Android (ASTC)): D:/GitHub/VALORANT/Plugins/DataConfig/Source/DataConfigEngineExtra/Private/DataConfig/EngineExtra/SerDe/DcJsonBlueprintLibrary.cpp(149,137): error: use of undeclared identifier 'HandleBase64BlobDeserialize'
UATHelper: Packaging (Android (ASTC)):                 Deserializer->AddPredicatedHandler(FDcDeserializePredicate::CreateStatic(PredicateIsBase64Blob), FDcDeserializeDelegate::CreateStatic(HandleBase64BlobDeserialize));
UATHelper: Packaging (Android (ASTC)):                                                                                                                                                       ^
UATHelper: Packaging (Android (ASTC)): In file included from D:/GitHub/VALORANT/Plugins/DataConfig/Intermediate/Build/Android/a/UnrealGame/Development/DataConfigEngineExtra/Module.DataConfigEngineExtra.cpp:9:
UATHelper: Packaging (Android (ASTC)): D:/GitHub/VALORANT/Plugins/DataConfig/Source/DataConfigEngineExtra/Private/DataConfig/EngineExtra/SerDe/DcSerDeBlueprint.cpp(341,33): error: no member named 'HasMetaData' in 'UField'
UATHelper: Packaging (Android (ASTC)):         bIsBitFlags = ((UField*)Enum)->HasMetaData(TEXT("Bitflags"));
UATHelper: Packaging (Android (ASTC)):                       ~~~~~~~~~~~~~~~  ^
UATHelper: Packaging (Android (ASTC)): D:/GitHub/VALORANT/Plugins/DataConfig/Source/DataConfigEngineExtra/Private/DataConfig/EngineExtra/SerDe/DcSerDeBlueprint.cpp(451,33): error: no member named 'HasMetaData' in 'UField'
UATHelper: Packaging (Android (ASTC)):         bIsBitFlags = ((UField*)Enum)->HasMetaData(TEXT("Bitflags"));
UATHelper: Packaging (Android (ASTC)):                       ~~~~~~~~~~~~~~~  ^
UATHelper: Packaging (Android (ASTC)): 6 errors generated.
UATHelper: Packaging (Android (ASTC)): Total time in Parallel executor: 1.74 seconds
PackagingResults: Error: use of undeclared identifier 'HandleBase64BlobSerialize'
PackagingResults: Error: use of undeclared identifier 'PredicateIsBase64Blob'
PackagingResults: Error: use of undeclared identifier 'HandleBase64BlobDeserialize'
PackagingResults: Error: no member named 'HasMetaData' in 'UField'
PackagingResults: Error: no member named 'HasMetaData' in 'UField'

**Comment by jagt** [comment]
I took a quick look this is a Shipping configuration issue. I'll push for a fix soon

**Comment by jagt** [comment]
I've just pushed 1.6.2 here:
<https://github.com/slowburn-dev/DataConfig/releases/tag/1.6.2>

Can you try this and see if it works?

**Comment by yingnierxiao** [comment]
> I've just pushed 1.6.2 here: https://github.com/slowburn-dev/DataConfig/releases/tag/1.6.2
> 
> Can you try this and see if it works?

ok,it work
