### ISSUE TITLE
json data ,may int or may int array ，how can i set the type,

### ISSUE THREAD

**Issue by yingnierxiao** [slowburn-dev/DataConfig#11]
"Rotate": [
        -1.8166382312774658,
        -0.30297359824180603,
        3.120814561843872
      ],

"Rotate": 3.006002426147461,

in c# can use public object Rotate { get; set; }

**Comment by jagt** [comment]
For usage you can reach us by this mail: <hislowburn@gmail.com>

**Comment by yingnierxiao** [comment]
> For usage you can reach us by this mail: [hislowburn@gmail.com](mailto:hislowburn@gmail.com)

i has send mail to you
