### ISSUE TITLE
arrays defined in blueprint are not reset before deserializing

### ISSUE THREAD

**Issue by endseeker** [slowburn-dev/DataConfig#12]
you end up with 2x the number of elements. 
steps to repro in the unit test
  1. add an array to the test DC_TEST("DataConfig.EngineExtra.BPClassInstance"):
      `	FString Str = TEXT(R"(
		{
			"StrField" : "Foo",
			"BPEnumField" : "Baz",
			"IntField" : 345,
			"TestArray" : [8, 9]
		}

	)");`

  2. add an array to blueprint in Unreal ("/DataConfig/DcFixture/DcTestBlueprintClassAlpha") 
  3. notice the extra 0's added after reading back the string.
      `{
    "StrField" : "Foo",
    "BPEnumField" : "Baz",
    "IntField" : 345,
    "TestArray" : [
        8,
        9,
        0,
        0
    ]
}
`

**Comment by jagt** [comment]
Can you check that did you add 2 default values in your `DcTestBlueprintClassAlpha` added array?

Only in this case it would have the additional elements. This is indeed confusing and I'll get a fix for this soon.

**Comment by jagt** [comment]
I just pushed [1.7.1](https://github.com/slowburn-dev/DataConfig/releases/tag/1.7.1) which should've addressed the issue.

**Comment by endseeker** [comment]
thanks.
