### ISSUE TITLE
not initialized properly

### ISSUE THREAD

**Issue by earthstorm2015** [slowburn-dev/DataConfig#13]
Error        LogAutomationTest         LogClass: FloatProperty FDcVector2D::X is not initialized properly. Module:DataConfigExtra File:Private/DataConfig/Extra/Benchmark/DcBenchmarkFixture1.h
Error        LogAutomationTest         LogClass: FloatProperty FDcVector2D::Y is not initialized properly. Module:DataConfigExtra File:Private/DataConfig/Extra/Benchmark/DcBenchmarkFixture1.h
Error        LogAutomationTest         LogClass: IntProperty FDcCorpusEntry::year is not initialized properly. Module:DataConfigExtra File:Private/DataConfig/Extra/Benchmark/DcBenchmarkFixture1.h
Error        LogAutomationTest         LogClass: IntProperty FDcTestExtraRenameFrom1::FromInt1 is not initialized properly. Module:DataConfigExtra File:Public/DataConfig/Extra/Deserialize/DcDeserializeRenameStructFieldNames.h
Error        LogAutomationTest         LogClass: IntProperty FDcTestExtraRenameTo1::ToInt1 is not initialized properly. Module:DataConfigExtra File:Public/DataConfig/Extra/Deserialize/DcDeserializeRenameStructFieldNames.h
Error        LogAutomationTest         LogClass: FloatProperty FDcStructShapeRectangle::Height is not initialized properly. Module:DataConfigExtra File:Public/DataConfig/Extra/Types/DcExtraTestFixtures.h
Error        LogAutomationTest         LogClass: FloatProperty FDcStructShapeRectangle::Width is not initialized properly. Module:DataConfigExtra File:Public/DataConfig/Extra/Types/DcExtraTestFixtures.h
Error        LogAutomationTest         LogClass: FloatProperty FDcStructShapeCircle::Radius is not initialized properly. Module:DataConfigExtra File:Public/DataConfig/Extra/Types/DcExtraTestFixtures.h
Error        LogAutomationTest         LogClass: IntProperty FDcExtraSimpleStruct::Id is not initialized properly. Module:DataConfigExtra File:Public/DataConfig/Extra/Types/DcExtraTestFixtures.h

How to solve these problems？

**Comment by jagt** [comment]
Hi. Where do you get these logs?

**Comment by earthstorm2015** [comment]
When I put the release plugin into the project and then opened the Rider editor, I received so many errors. The UE version is 5.3; Plugin version is DataConfig_1.7.0_UE5.0-5.4.zip；
But I am using version 1.7.1 today and have not encountered this issue again。
