### ISSUE TITLE
UE5Rules error

### ISSUE THREAD

**Issue by yingnierxiao** [slowburn-dev/DataConfig#8]
Couldn't find target rules file for target 'DataConfigHeadless' in rules assembly 'UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

Location: D:\Program Files\Epic Games\UE_5.4\Engine\Intermediate\Build\BuildRules\UE5Rules.dll

**Comment by jagt** [comment]
If you're using official 5.4 from epic store there's a compilation error. I'll push a new version soon.

**Comment by yingnierxiao** [comment]
> If you're using official 5.4 from epic store there's a compilation error. I'll push a new version soon.

yes ,it's official 5.4 version
