### ISSUE TITLE
static_assert(sizeof(FTextAccess) == sizeof(FText), "FTextAccess stale");  build error

### ISSUE THREAD

**Issue by yingnierxiao** [slowburn-dev/DataConfig#9]
static_assert(sizeof(FTextAccess) == sizeof(FText), "FTextAccess stale");

Error        LogClass                  FloatProperty FDcVector2D::X is not initialized properly. Module:DataConfigExtra File:Private/DataConfig/Extra/Benchmark/DcBenchmarkFixture1.h
Error        LogClass                  FloatProperty FDcVector2D::Y is not initialized properly. Module:DataConfigExtra File:Private/DataConfig/Extra/Benchmark/DcBenchmarkFixture1.h
Error        LogClass                  IntProperty FDcCorpusEntry::year is not initialized properly. Module:DataConfigExtra File:Private/DataConfig/Extra/Benchmark/DcBenchmarkFixture1.h
Error        LogClass                  IntProperty FDcTestExtraRenameFrom1::FromInt1 is not initialized properly. Module:DataConfigExtra File:Public/DataConfig/Extra/Deserialize/DcDeserializeRenameStructFieldNames.h
Error        LogClass                  IntProperty FDcTestExtraRenameTo1::ToInt1 is not initialized properly. Module:DataConfigExtra File:Public/DataConfig/Extra/Deserialize/DcDeserializeRenameStructFieldNames.h
Error        LogClass                  FloatProperty FDcStructShapeRectangle::Height is not initialized properly. Module:DataConfigExtra File:Public/DataConfig/Extra/Types/DcExtraTestFixtures.h
Error        LogClass                  FloatProperty FDcStructShapeRectangle::Width is not initialized properly. Module:DataConfigExtra File:Public/DataConfig/Extra/Types/DcExtraTestFixtures.h

**Comment by jagt** [comment]
I've just pushed 1.6.1 and it should've fixed the issue.

<https://github.com/slowburn-dev/DataConfig/releases/tag/1.6.1>
